import { and, eq, gte } from 'drizzle-orm';
import { htmlToText, replySubject } from '../../../shared/text';
import type { Db } from '../../db/client';
import { autoReplyLog, contacts, type Domain, type Mailbox, type Message } from '../../db/schema';
import type { AppEnv } from '../../env';
import { newId } from '../../lib/crypto';
import { composeMessage } from '../outbound/compose';
import { queueSend } from '../outbound/deliver';
import type { ParsedMail } from '../providers/types';
import { isAutoGenerated } from './classify';

const REPLY_WINDOW_MS = 24 * 60 * 60 * 1000;

/**
 * Sends the mailbox's vacation responder once per sender per 24h, skipping
 * anything that looks automated so two responders never loop.
 */
export async function maybeAutoReply(env: AppEnv, db: Db, mailbox: Mailbox, domain: Domain, mail: ParsedMail, stored: Message): Promise<boolean> {
  const vacation = mailbox.vacation;
  if (!vacation?.enabled) return false;
  const now = Date.now();
  if (vacation.startsAt && new Date(vacation.startsAt).getTime() > now) return false;
  if (vacation.endsAt && new Date(vacation.endsAt).getTime() < now) return false;
  if (isAutoGenerated(mail)) return false;
  if (mail.headers['x-mailcove-forwarded']) return false;
  const sender = mail.replyTo[0]?.email || mail.from.email;
  if (!sender || sender === mailbox.address) return false;
  if (sender.endsWith(`@${domain.name}`) && sender.split('@')[0] === mailbox.localPart) return false;

  if (vacation.contactsOnly && mailbox.ownerUserId) {
    const known = await db
      .select({ id: contacts.id })
      .from(contacts)
      .where(and(eq(contacts.userId, mailbox.ownerUserId), eq(contacts.email, sender)))
      .get();
    if (!known) return false;
  }

  const recent = await db
    .select({ id: autoReplyLog.id })
    .from(autoReplyLog)
    .where(and(eq(autoReplyLog.mailboxId, mailbox.id), eq(autoReplyLog.recipient, sender), gte(autoReplyLog.sentAt, new Date(now - REPLY_WINDOW_MS))))
    .get();
  if (recent) return false;

  await db
    .insert(autoReplyLog)
    .values({ id: newId(), mailboxId: mailbox.id, recipient: sender, sentAt: new Date() })
    .onConflictDoUpdate({ target: [autoReplyLog.mailboxId, autoReplyLog.recipient], set: { sentAt: new Date() } });

  const subject = vacation.subject?.trim() || replySubject(mail.subject || '(no subject)');
  const html = vacation.bodyHtml || '<p>Thanks for your message. I am currently away and will reply when I return.</p>';
  const reply = await composeMessage(db, {
    mailbox,
    domain,
    authorUserId: null,
    from: { email: mailbox.address, name: mailbox.displayName ?? null },
    to: [{ email: sender, name: mail.from.name ?? null }],
    subject,
    html,
    text: htmlToText(html),
    replyToMessageId: stored.id,
    sendMode: 'reply',
    headers: { 'Auto-Submitted': 'auto-replied', 'X-Auto-Response-Suppress': 'All', Precedence: 'auto_reply' },
    bucket: env.STORAGE,
  });
  await queueSend(env, db, reply, 0);
  return true;
}
