import { domainOf } from '../../../shared/address';
import type { AuthResults, Category, ListUnsubscribe } from '../../../shared/types';
import type { ParsedMail } from '../providers/types';

export function parseAuthResults(mail: ParsedMail): AuthResults {
  const header = mail.headers['authentication-results'] ?? mail.headers['arc-authentication-results'] ?? '';
  const pick = (name: string): string | null => {
    const m = header.match(new RegExp(`\\b${name}=([a-z]+)`, 'i'));
    return m ? m[1]!.toLowerCase() : null;
  };
  const spf = pick('spf') ?? (mail.headers['received-spf']?.split(/\s/)[0]?.toLowerCase() ?? null);
  return { spf, dkim: pick('dkim'), dmarc: pick('dmarc') };
}

export function parseListUnsubscribe(mail: ParsedMail): ListUnsubscribe | null {
  const header = mail.headers['list-unsubscribe'];
  if (!header) return null;
  const urls = [...header.matchAll(/<([^<>]+)>/g)].map((m) => m[1]!.trim());
  const http = urls.find((u) => /^https?:\/\//i.test(u)) ?? null;
  const mailto = urls.find((u) => /^mailto:/i.test(u)) ?? null;
  if (!http && !mailto) return null;
  const oneClick = /one-click/i.test(mail.headers['list-unsubscribe-post'] ?? '');
  return { http, mailto, oneClick };
}

export type SpamVerdict = { isSpam: boolean; score: number; reasons: string[] };

/**
 * Lightweight spam heuristics. Providers already reject the worst offenders
 * (RBLs, failing DMARC); this catches authentication failures and obvious
 * junk so it lands in Spam instead of Inbox.
 */
export function assessSpam(mail: ParsedMail, auth: AuthResults): SpamVerdict {
  const reasons: string[] = [];
  let score = 0;

  const flag = (mail.headers['x-spam-flag'] ?? '').toLowerCase();
  const status = (mail.headers['x-spam-status'] ?? '').toLowerCase();
  if (flag === 'yes' || status.startsWith('yes')) {
    score += 5;
    reasons.push('upstream spam flag');
  }
  if (auth.dmarc === 'fail') {
    score += 3;
    reasons.push('DMARC fail');
  }
  if (auth.spf === 'fail' && auth.dkim !== 'pass') {
    score += 2;
    reasons.push('SPF fail without DKIM');
  }
  if (!mail.from.email) {
    score += 2;
    reasons.push('missing sender');
  }
  const subject = mail.subject.toLowerCase();
  const junkPhrases = ['viagra', 'casino', 'lottery winner', 'you have been selected', 'claim your prize', 'crypto giveaway', 'wire transfer urgently'];
  if (junkPhrases.some((p) => subject.includes(p))) {
    score += 3;
    reasons.push('junk subject');
  }
  if (/^[A-Z\s!$]{12,}$/.test(mail.subject) && mail.subject.length > 12) {
    score += 1;
    reasons.push('shouting subject');
  }
  const replyTo = mail.replyTo[0]?.email;
  if (replyTo && domainOf(replyTo) !== domainOf(mail.from.email) && /(gmail|outlook|hotmail|yahoo)\./.test(domainOf(replyTo))) {
    score += 1;
    reasons.push('reply-to mismatch');
  }
  return { isSpam: score >= 4, score, reasons };
}

const SOCIAL_DOMAINS = ['facebookmail.com', 'linkedin.com', 'twitter.com', 'x.com', 'instagram.com', 'pinterest.com', 'tiktok.com', 'reddit.com', 'discord.com', 'nextdoor.com', 'snapchat.com', 'threads.net', 'strava.com', 'meetup.com'];
const UPDATE_KEYWORDS = ['receipt', 'invoice', 'order', 'shipped', 'delivery', 'statement', 'payment', 'confirm', 'verification', 'security alert', 'password', 'your account', 'reservation', 'booking', 'itinerary', 'ticket'];
const PROMO_KEYWORDS = ['sale', '% off', 'discount', 'deal', 'offer', 'save', 'coupon', 'free shipping', 'limited time', 'new arrivals', 'last chance', 'exclusive', 'black friday', 'newsletter'];

/** Gmail-style inbox categories from list headers, sender domain and subject vocabulary. */
export function categorize(mail: ParsedMail): Category {
  const fromDomain = domainOf(mail.from.email);
  const subject = mail.subject.toLowerCase();
  const listId = mail.headers['list-id'];
  const precedence = (mail.headers['precedence'] ?? '').toLowerCase();
  const isBulk = Boolean(listId) || precedence === 'bulk' || precedence === 'list' || Boolean(mail.headers['list-unsubscribe']);

  if (SOCIAL_DOMAINS.some((d) => fromDomain === d || fromDomain.endsWith(`.${d}`))) return 'social';
  if (/^(no-?reply|notifications?|alerts?|updates?|billing|receipts?|orders?|support|security|account)@/i.test(mail.from.email) && !PROMO_KEYWORDS.some((k) => subject.includes(k))) {
    return 'updates';
  }
  if (listId && /(googlegroups|groups\.io|discourse|forum|lists?\.)/i.test(listId)) return 'forums';
  if (isBulk) {
    if (PROMO_KEYWORDS.some((k) => subject.includes(k))) return 'promotions';
    if (UPDATE_KEYWORDS.some((k) => subject.includes(k))) return 'updates';
    return 'promotions';
  }
  if (UPDATE_KEYWORDS.some((k) => subject.includes(k)) && /^(no-?reply|noreply|do-?not-?reply|notifications?|mailer|auto)/i.test(mail.from.email)) return 'updates';
  return 'primary';
}

export function isAutoGenerated(mail: ParsedMail): boolean {
  const auto = (mail.headers['auto-submitted'] ?? 'no').toLowerCase();
  if (auto && auto !== 'no') return true;
  if (mail.headers['x-auto-response-suppress']) return true;
  if (mail.headers['x-autoreply'] || mail.headers['x-autorespond']) return true;
  const precedence = (mail.headers['precedence'] ?? '').toLowerCase();
  if (precedence === 'bulk' || precedence === 'junk' || precedence === 'list') return true;
  if (mail.headers['list-id']) return true;
  if (/^(mailer-daemon|postmaster|no-?reply|noreply|do-?not-?reply|bounce|bounces)[@+-]/i.test(mail.from.email)) return true;
  return false;
}
