import { describe, expect, it } from 'vitest';
import { assessSpam, categorize, isAutoGenerated, parseAuthResults, parseListUnsubscribe } from '../../src/worker/mail/inbound/classify';
import type { ParsedMail } from '../../src/worker/mail/providers/types';

function mail(over: Partial<ParsedMail> = {}): ParsedMail {
  return {
    messageId: '<m@x>',
    inReplyTo: null,
    references: null,
    from: { email: 'friend@example.com', name: 'Friend' },
    to: [],
    cc: [],
    bcc: [],
    replyTo: [],
    subject: 'Lunch tomorrow',
    date: new Date(),
    text: 'hi',
    html: null,
    headers: {},
    attachments: [],
    sizeBytes: 100,
    ...over,
  };
}

describe('classify inbound mail', () => {
  it('parses Authentication-Results and List-Unsubscribe', () => {
    const m = mail({
      headers: {
        'authentication-results': 'mx; dkim=pass; spf=fail; dmarc=fail',
        'list-unsubscribe': '<mailto:unsub@x.test>, <https://x.test/unsub>',
        'list-unsubscribe-post': 'List-Unsubscribe=One-Click',
      },
    });
    expect(parseAuthResults(m)).toEqual({ spf: 'fail', dkim: 'pass', dmarc: 'fail' });
    expect(parseListUnsubscribe(m)).toEqual({ http: 'https://x.test/unsub', mailto: 'mailto:unsub@x.test', oneClick: true });
  });

  it('flags spam on upstream + DMARC fail + junk subject', () => {
    const junk = mail({
      subject: 'CLAIM YOUR PRIZE casino',
      headers: { 'x-spam-flag': 'YES', 'authentication-results': 'mx; dmarc=fail; spf=fail' },
    });
    const verdict = assessSpam(junk, parseAuthResults(junk));
    expect(verdict.isSpam).toBe(true);
    expect(verdict.score).toBeGreaterThanOrEqual(4);
  });

  it('categorizes social, updates, promotions, forums, primary', () => {
    expect(categorize(mail({ from: { email: 'notify@facebookmail.com', name: null } }))).toBe('social');
    expect(categorize(mail({ from: { email: 'noreply@shop.test', name: null }, subject: 'Your receipt', headers: { 'list-unsubscribe': '<https://x>' } }))).toBe('updates');
    expect(categorize(mail({ from: { email: 'deals@shop.test', name: null }, subject: '50% off sale', headers: { precedence: 'bulk' } }))).toBe('promotions');
    expect(categorize(mail({ headers: { 'list-id': '<topic.discourse.example.com>' } }))).toBe('forums');
    expect(categorize(mail())).toBe('primary');
  });

  it('detects auto-generated mail', () => {
    expect(isAutoGenerated(mail({ headers: { 'auto-submitted': 'auto-replied' } }))).toBe(true);
    expect(isAutoGenerated(mail({ from: { email: 'mailer-daemon@example.com', name: null } }))).toBe(true);
    expect(isAutoGenerated(mail())).toBe(false);
  });
});
